# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ddpg.yml
program: train_sb3_wandb_ddpg.py
method: grid
name: rel_ik_sb3_ddpg_ur5e_reach_0_05_pose_grid_search_network_architecture
metric:
  goal: maximize
  name: rollout/ep_rew_mean

parameters:
  seed:
    values: [42, 24]

  num_envs:
    value: 2048

  device:
    value: "cuda:0"

  n_timesteps: # iteration * n_steps * nenvs: 400 * 64 * 8192 = 209715200
    value: 104857600

  policy:
    value: 'MlpPolicy'

  batch_size:
    value: 256 

  gamma:
    value: 0.95

  learning_rate:
    value: 0.0001

  train_freq:
    value: 4

  gradient_steps:
    value: 4

  buffer_size: 
    value: 1000000

  learning_starts: 
    value: 1000

  tau: 
    value: 0.02

  action_noise:
    value: NormalActionNoise # values: [NormalActionNoise, OrnsteinUhlenbeckActionNoise]

  action_sigma:
    value: 0.01

  # optimize_memory_usage:
  #   value: True

  policy_kwargs:
    parameters:
      activation_fn: 
        value: nn.Tanh
      net_arch:
        values: [[300, 300], [256, 128], [128, 64]] # value: [256, 128]

  normalize_input:
    value: False # values: [True, False]

  normalize_value:
    value: False

  clip_obs:
    value: 50.0