program: train_sb3_wandb.py
method: grid
name: rel_ik_sb3_ppo_ur5e_reach_0_05_pose
metric:
  goal: maximize
  name: rollout/ep_rew_mean

parameters:
  seed:
    value: 42

  n_timesteps: # iteration * n_steps * nenvs: 400 * 64 * 8192 = 209715200
    value: 209715200

  policy:
    value: 'MlpPolicy'

  n_steps:
    value: 64

  batch_size:
    value: 16384

  gae_lambda:
    value: 0.95

  gamma:
    value: 0.99

  n_epochs:
    value: 8

  ent_coef: # Possibly change this to encourange more exploration
    values: [0,05, 0.01]

  vf_coef:
    values: [0.1, 0.01]

  learning_rate:
    values: [1e-4, 3e-4]

  clip_range:
    values: [0.2, 0.3]

  policy_kwargs:
    parameters:
      activation_fn: 
        value: nn.ELU
      net_arch:
        parameters:
          pi:
            value: [128, 64]
          vf:
            value: [128, 64]

  target_kl:
    value: 0.02

  max_grad_norm:
    value: 1.0

  normalize_input:
    value: False

  normalize_value:
    value: False

  clip_obs:
    value: 50.0