program: train_sb3_wandb.py
method: grid
name: rel_ik_sb3_ppo_ur5e_reach_0_05_position
metric:
  goal: maximize
  name: rollout/ep_rew_mean

parameters:
  seed:
    value: 42

  n_timesteps: # iteration * n_steps * nenvs: 400 * 64 * 8192 = 209715200
    value: 209715200

  policy:
    value: 'MlpPolicy'

  n_steps:
    value: 64

  batch_size:
    values: [2048, 8192, 16384]

  gae_lambda:
    value: 0.95

  gamma:
    value: 0.99

  n_epochs:
    value: 8

  ent_coef: # Possibly change this to encourange more exploration
    values: [0.01, 0.001]

  vf_coef:
    value: 0.1

  learning_rate:
    value: 1e-4

  clip_range:
    value: 0.2

  policy_kwargs:
    parameters:
      activation_fn: 
        value: nn.ELU
      net_arch:
        parameters:
          pi:
            value: [128, 64]
          vf:
            value: [128, 64]

  target_kl:
    value: 0.02

  max_grad_norm:
    value: 1.0

  normalize_input:
    value: False

  normalize_value:
    values: [True, False]

  clip_obs:
    value: 50.0