# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml
seed: 42

# n_timesteps = total gradient updates * train_freq/gradient_steps = 52428800
n_timesteps: 209715200
policy: 'MlpPolicy'
batch_size: 16384
gamma: 0.95
ent_coef: 0.01 #"auto"
learning_rate: !!float 1e-3
train_freq: 4
gradient_steps: 4
target_update_interval: 1
# target_entropy: -6 # - action space dimensions (3 translational components, 3 rotational components, 1 binary gripper)
buffer_size: 1000000
learning_starts: 1000
tau: 0.02
use_sde: True
policy_kwargs: "dict(
                  activation_fn=nn.ELU,
                  net_arch=[128, 64]
                )"

# Uses VecNormalize class to normalize obs
normalize_input: False
# Uses VecNormalize class to normalize rew
normalize_value: False
clip_obs: 50.0