wandb_version: 1

batch_size:
  value: 16384
clip_obs:
  value: 50
clip_range:
  value: 0.2
ent_coef:
  value: 0
gae_lambda:
  value: 0.95
gamma:
  value: 0.95
learning_rate:
  value: 0.0003
max_grad_norm:
  value: 1
n_epochs:
  value: 8
n_steps:
  value: 64
n_timesteps:
  value: 104857600
normalize_input:
  value: false
normalize_value:
  value: false
num_envs:
  value: 2048
policy:
  value: MlpPolicy
policy_kwargs:
  value:
    activation_fn: nn.Tanh
    net_arch:
      pi:
      - 256
      - 128
      vf:
      - 256
      - 128
seed:
  value: 24
target_kl:
  value: 0.02
vf_coef:
  value: 0.1
