wandb_version: 1

batch_size:
  value: 8192
clip_obs:
  value: 50
clip_range:
  value: 0.2
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.95
gamma:
  value: 0.99
learning_rate:
  value: 0.0001
max_grad_norm:
  value: 1
n_epochs:
  value: 8
n_steps:
  value: 64
n_timesteps:
  value: 209715200
normalize_input:
  value: false
normalize_value:
  value: true
policy:
  value: MlpPolicy
policy_kwargs:
  value:
    activation_fn: nn.ELU
    net_arch:
      pi:
      - 128
      - 64
      vf:
      - 128
      - 64
seed:
  value: 42
target_kl:
  value: 0.02
vf_coef:
  value: 0.1
